#BEGIN VOXEL STUFF
map_type: voxel
origin_z: 0.0
z_voxels: 16
z_resolution: 0.1125
unknown_cost_value: 0
unknown_threshold: 15
mark_threshold: 0
#END VOXEL STUFF

transform_tolerance: 0.2
obstacle_range: 6
raytrace_range: 10
inflation_radius: 0.45
# original 0.55

# BEGIN VOXEL STUFF
#observation_sources: base_scan_marking base_scan tilt_scan_marking tilt_scan
observation_sources: base_scan_marking base_scan
#observation_sources: base_scan_marking base_scan ground_object_cloud
#observation_sources: kinect

base_scan_marking: {sensor_frame: base_laser_link, topic: /base_scan_marking, data_type: PointCloud2, expected_update_rate: 0.2,
  observation_persistence: 0.0, marking: true, clearing: false, min_obstacle_height: 0.08, max_obstacle_height: 2.0}

base_scan: {sensor_frame: base_laser_link, topic: /base_scan, data_type: LaserScan, expected_update_rate: 0.2,
             observation_persistence: 0.0, marking: false, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 2.0}

tilt_scan_marking: {sensor_frame: laser_tilt_link, topic: /tilt_scan_marking, data_type: PointCloud2, expected_update_rate: 0.2,
  observation_persistence: 0.0, marking: true, clearing: false, min_obstacle_height: 0.08, max_obstacle_height: 2.0}

tilt_scan: {sensor_frame: laser_tilt_link, topic: /tilt_scan, data_type: LaserScan, expected_update_rate: 0.2,
             observation_persistence: 0.0, marking: false, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 2.0}

# END VOXEL STUFF
