local_costmap:
  #Independent settings for the local costmap
  publish_voxel_map: false
  global_frame: odom_combined
  robot_base_frame: base_footprint
  update_frequency: 20.0
  publish_frequency: 0.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.025
  origin_x: 0.0
  origin_y: 0.0
